# Generated by Django 2.1.3 on 2019-05-17 13:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a car name', max_length=200)),
                ('price', models.IntegerField(help_text='Enter a car price')),
                ('image', models.ImageField(upload_to='autos')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Auto')),
            ],
        ),
    ]
