# Generated by Django 2.2.1 on 2019-05-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190522_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='image',
            field=models.CharField(help_text='Enter a local path for static image of the car', max_length=200),
        ),
    ]
